/*389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> mp;
        for(char c:s)
        {
            mp[c]++;
        }
        for(char c:t)
        {
            if(mp.find(c)!=mp.end())
            {
                mp[c]--;
                if(mp[c]==0)
                    mp.erase(c);
            }
            else
                return c;
        }
        return ' ';
    }
};